name: Enforce Dependabot Config
on:
  push:
    branches: [main]
    paths: [".github/dependabot.yml"]
  pull_request:
    paths: [".github/dependabot.yml"]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  check:
    permissions:
      contents: read
    uses: baobab-platform/shared/.github/workflows/enforce-dependabot-config.yml@31de2bc3dcd56128c019c640dc7e12c10ae9ca69 # v2.3.0
