name: Enforce Dependabot Config
on:
  push:
    branches: [main]
    paths: [".github/dependabot.yml"]
  pull_request:
    paths: [".github/dependabot.yml"]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  check:
    permissions:
      contents: read
    uses: baobab-platform/shared/.github/workflows/enforce-dependabot-config.yml@f7466cc89a17c0b6e02b5a1e5fce3ce76073a718 # v1.1.0
